
import './globals.css';
import Script from 'next/script';
import { Heebo, Jost } from 'next/font/google';
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

export const metadata = {
  title: "Diligent Soft IT - Digital Marketing Agency",
  description: "Generated by create next app",
  keywords: ["digital marketing", "seo", "web development"]
};

const heebo = Heebo({ subsets: ['latin'], weight: ['400', '500'] });
const jost = Jost({ subsets: ['latin'], weight: ['500', '600', '700'] });

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-scroll-behavior="smooth">
      <head>
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link href="/images/logo.jpg" rel="icon" />

        <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet" />
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet" />

      </head>
      <body className={`${heebo.className} ${jost.className}`} cz-shortcut-listen="true">
        <ToastContainer position="bottom-right" autoClose={3000} theme="colored" />
        {children}
        <Script src="https://code.jquery.com/jquery-3.4.1.min.js"></Script>
        <Script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></Script>
        <Script src="/lib/wow/wow.min.js"></Script>
        <Script src="/lib/easing/easing.min.js"></Script>
        <Script src="/lib/waypoints/waypoints.min.js"></Script>
        <Script src="/lib/counterup/counterup.min.js"></Script>
        <Script src="/lib/owlcarousel/owl.carousel.min.js"></Script>
        <Script src="/lib/isotope/isotope.pkgd.min.js"></Script>
        <Script src="/lib/lightbox/js/lightbox.min.js"></Script>
        <Script src="/js/main.js"></Script>
      </body>
    </html>
  );
}